language: "node_js"
node_js:
  - "node"
  - "12"
env:
  - TEST_DIR=api
script: cd $TEST_DIR && npm install && npm test
services:
  - docker
os:
  - linux
before_script:
  - ./api/scripts/run_couchdb_on_travis.sh
after_script:
  - ./api/scripts/stop_couchdb_on_travis.sh

