language: "node_js"
node_js:
  - "node"
  - "14"
env:
  - TEST_DIR=api
script: cd $TEST_DIR && npm install && npm test
services:
  - docker
os:
  - linux
before_script:
  - ./api/scripts/run_dynamo_db.sh
after_script:
  - ./api/scripts/stop_dynamo_db.sh

